name: Weekly Scraping Job

on:
  schedule:
    # Runs every Monday at 00:00 UTC
    - cron: "0 0 * * 1"

  workflow_dispatch: # Allows manual triggering of the workflow.

jobs:
  scrape_billionaires:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run the scraping script
    - name: Run the scraper
      run: python Forbes-Code.py

    # Step 5: Upload the CSV file as an artifact
    - name: Upload CSV file
      uses: actions/upload-artifact@v3
      with:
        name: billionaires_data
        path: billionaires_data.csv

